CC = gcc
CFLAGS = -Wall -g



all: server client

server: 
	$(CC) $(CFLAGS) -o server server.c server_functions.c
	
# client: 
# 	$(CC) $(CFLAGS) -o client client.c client_functions.c

clean: 
	rm -f server client


